name: Setup Artifactory
description: GitHub Action to configure Conda and pip to use Met Office Artifactory.
author: Payton Leedham, Chris Bunney
inputs:
  username:
    description: Artifactory username
    required: false  # Note `required` doesn't actually do anything: https://github.com/actions/runner/issues/1070

  api-key:
    description: Artifactory API key or Identity Token
    required: true

  check-creds:
    description: Whether to check credentials validity
    required: true
    default: false

  setup-conda-forge:
    description: Add conda-forge as a channel in preference to Anaconda defaults
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Setup Artifactory
      shell: bash
      env:
        USERNAME: ${{ inputs.username }}
        API_KEY: ${{ inputs.api-key }}
        SETUP_CONDA_FORGE: ${{ inputs.setup-conda-forge }}
        ACTION_PATH: ${{ github.action_path }}
        CHECK_CREDS: ${{ inputs.check-creds }}
      run: bash "${ACTION_PATH}/action.sh"
